services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    networks:
      traefik-network:
    command: >-
      --entryPoints.web.address=:80
      --entryPoints.web.http.redirections.entrypoint.to=web-secure
      --entryPoints.web.http.redirections.entrypoint.scheme=https
      --entryPoints.web-secure.address=:443
      --api=true
      --api.dashboard=true
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --providers.file.directory=/srv/configs
      --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/srv
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.services.traefik.loadBalancer.server.port=8080

#  wasm:
#    build:
#      context: .
#      dockerfile: frontend.dockerfile
#      secrets:
#        - WEBSOCKET_SERVER_ADDRESS
#    networks:
#      - traefik-network
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.game.entryPoints=web-secure
#      - traefik.http.routers.game.rule=Host(`game.docker.localhost`)
#      - traefik.http.routers.game.tls=true
#      - traefik.http.services.game.loadBalancer.server.port=80

  server:
    build:
      context: .
      dockerfile: backend.dockerfile
      secrets:
        - API_SERVER_ADDRESS
        - COMFYUI_HOST_URL
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      # Websocket
      - traefik.http.routers.websocket.service=websocket
      - traefik.http.routers.websocket.entryPoints=web-secure
      - traefik.http.routers.websocket.rule=Host(`websocket.docker.localhost`)
      - traefik.http.routers.websocket.tls=true
      - traefik.http.services.websocket.loadBalancer.server.port=9001
      # API
      - traefik.http.routers.api.service=api
      - traefik.http.routers.api.entryPoints=web-secure
      - traefik.http.routers.api.rule=Host(`api.docker.localhost`)
      - traefik.http.routers.api.tls=true
      - traefik.http.services.api.loadBalancer.server.port=3000
networks:
  traefik-network:

secrets:
  WEBSOCKET_SERVER_ADDRESS:
    environment: wss://websocket.docker.localhost
  API_SERVER_ADDRESS:
    environment: https://api.docker.localhost
  COMFYUI_HOST_URL:
    environment: http://192.168.50.230:8188
