services:
  #  wasm:
  #    build:
  #      context: .
  #      dockerfile: frontend.dockerfile
  #      secrets:
  #        - WEBSOCKET_SERVER_ADDRESS
  #    networks:
  #      - traefik-network
  #    deploy:
  #      update_config:
  #        order: start-first
  #      labels:
  #        - traefik.enable=true
  #        - traefik.http.routers.game.entryPoints=web-secure
  #        - traefik.http.routers.game.rule=Host(`imaginarium.dearbook.ai`)
  #        - traefik.http.routers.game.tls=true
  #        - traefik.http.services.game.loadBalancer.server.port=80

  server:
    image: ${REGISTRY}/imaginarium/server:latest
    networks:
      - traefik-network
    deploy:
      update_config:
        order: start-first
      labels:
        - traefik.enable=true
        # Websocket
        - traefik.http.routers.websocket.service=websocket
        - traefik.http.routers.websocket.entryPoints=web-secure
        - traefik.http.routers.websocket.rule=Host(`websocket.imaginarium.dearbook.ai`)
        - traefik.http.routers.websocket.tls=true
        - traefik.http.services.websocket.loadBalancer.server.port=9001
        # API
        - traefik.http.routers.api.service=api
        - traefik.http.routers.api.entryPoints=web-secure
        - traefik.http.routers.api.rule=Host(`api.imaginarium.dearbook.ai`)
        - traefik.http.routers.api.tls=true
        - traefik.http.services.api.loadBalancer.server.port=3000

networks:
  traefik-network:
    external: true
