[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lib]
name = "shared"

[dependencies]
#bincode = { version = "1.3.2" }
serde = { version = "1.0.219", features = ["derive"] }
#bevy_simplenet = { version = "0.15.2", features = ["client", "bevy"] }